/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaCommuneRouteImport } from './routes/ma-commune'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AbonnementsRouteImport } from './routes/abonnements'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api.public.payments.webhook'
import { Route as ApiPublicOutagesIngestRouteImport } from './routes/api.public.outages.ingest'
import { Route as ApiPublicJobsSendTrialEmailsRouteImport } from './routes/api.public.jobs.send-trial-emails'
import { Route as ApiPublicJobsScrapeSocialSignalsRouteImport } from './routes/api.public.jobs.scrape-social-signals'
import { Route as ApiPublicJobsScrapeSmgeagRouteImport } from './routes/api.public.jobs.scrape-smgeag'
import { Route as ApiPublicJobsScrapePlanningRouteImport } from './routes/api.public.jobs.scrape-planning'
import { Route as ApiPublicJobsScrapeAiHistoryRouteImport } from './routes/api.public.jobs.scrape-ai-history'
import { Route as ApiPublicJobsProcessReportsRouteImport } from './routes/api.public.jobs.process-reports'
import { Route as ApiPublicJobsGenerateForecastsRouteImport } from './routes/api.public.jobs.generate-forecasts'
import { Route as ApiPublicJobsDispatchNotificationsRouteImport } from './routes/api.public.jobs.dispatch-notifications'
import { Route as ApiPublicJobsCleanupHistoryRouteImport } from './routes/api.public.jobs.cleanup-history'
import { Route as ApiPublicJobsCheckPreventiveRouteImport } from './routes/api.public.jobs.check-preventive'
import { Route as ApiPublicJobsBackfillPlanningRouteImport } from './routes/api.public.jobs.backfill-planning'

const MaCommuneRoute = MaCommuneRouteImport.update({
  id: '/ma-commune',
  path: '/ma-commune',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementsRoute = AbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOutagesIngestRoute = ApiPublicOutagesIngestRouteImport.update({
  id: '/api/public/outages/ingest',
  path: '/api/public/outages/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsSendTrialEmailsRoute =
  ApiPublicJobsSendTrialEmailsRouteImport.update({
    id: '/api/public/jobs/send-trial-emails',
    path: '/api/public/jobs/send-trial-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsScrapeSocialSignalsRoute =
  ApiPublicJobsScrapeSocialSignalsRouteImport.update({
    id: '/api/public/jobs/scrape-social-signals',
    path: '/api/public/jobs/scrape-social-signals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsScrapeSmgeagRoute =
  ApiPublicJobsScrapeSmgeagRouteImport.update({
    id: '/api/public/jobs/scrape-smgeag',
    path: '/api/public/jobs/scrape-smgeag',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsScrapePlanningRoute =
  ApiPublicJobsScrapePlanningRouteImport.update({
    id: '/api/public/jobs/scrape-planning',
    path: '/api/public/jobs/scrape-planning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsScrapeAiHistoryRoute =
  ApiPublicJobsScrapeAiHistoryRouteImport.update({
    id: '/api/public/jobs/scrape-ai-history',
    path: '/api/public/jobs/scrape-ai-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsProcessReportsRoute =
  ApiPublicJobsProcessReportsRouteImport.update({
    id: '/api/public/jobs/process-reports',
    path: '/api/public/jobs/process-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsGenerateForecastsRoute =
  ApiPublicJobsGenerateForecastsRouteImport.update({
    id: '/api/public/jobs/generate-forecasts',
    path: '/api/public/jobs/generate-forecasts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsDispatchNotificationsRoute =
  ApiPublicJobsDispatchNotificationsRouteImport.update({
    id: '/api/public/jobs/dispatch-notifications',
    path: '/api/public/jobs/dispatch-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsCleanupHistoryRoute =
  ApiPublicJobsCleanupHistoryRouteImport.update({
    id: '/api/public/jobs/cleanup-history',
    path: '/api/public/jobs/cleanup-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsCheckPreventiveRoute =
  ApiPublicJobsCheckPreventiveRouteImport.update({
    id: '/api/public/jobs/check-preventive',
    path: '/api/public/jobs/check-preventive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsBackfillPlanningRoute =
  ApiPublicJobsBackfillPlanningRouteImport.update({
    id: '/api/public/jobs/backfill-planning',
    path: '/api/public/jobs/backfill-planning',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/abonnements': typeof AbonnementsRoute
  '/admin': typeof AdminRoute
  '/carte': typeof CarteRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/ma-commune': typeof MaCommuneRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/jobs/backfill-planning': typeof ApiPublicJobsBackfillPlanningRoute
  '/api/public/jobs/check-preventive': typeof ApiPublicJobsCheckPreventiveRoute
  '/api/public/jobs/cleanup-history': typeof ApiPublicJobsCleanupHistoryRoute
  '/api/public/jobs/dispatch-notifications': typeof ApiPublicJobsDispatchNotificationsRoute
  '/api/public/jobs/generate-forecasts': typeof ApiPublicJobsGenerateForecastsRoute
  '/api/public/jobs/process-reports': typeof ApiPublicJobsProcessReportsRoute
  '/api/public/jobs/scrape-ai-history': typeof ApiPublicJobsScrapeAiHistoryRoute
  '/api/public/jobs/scrape-planning': typeof ApiPublicJobsScrapePlanningRoute
  '/api/public/jobs/scrape-smgeag': typeof ApiPublicJobsScrapeSmgeagRoute
  '/api/public/jobs/scrape-social-signals': typeof ApiPublicJobsScrapeSocialSignalsRoute
  '/api/public/jobs/send-trial-emails': typeof ApiPublicJobsSendTrialEmailsRoute
  '/api/public/outages/ingest': typeof ApiPublicOutagesIngestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/abonnements': typeof AbonnementsRoute
  '/admin': typeof AdminRoute
  '/carte': typeof CarteRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/ma-commune': typeof MaCommuneRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/jobs/backfill-planning': typeof ApiPublicJobsBackfillPlanningRoute
  '/api/public/jobs/check-preventive': typeof ApiPublicJobsCheckPreventiveRoute
  '/api/public/jobs/cleanup-history': typeof ApiPublicJobsCleanupHistoryRoute
  '/api/public/jobs/dispatch-notifications': typeof ApiPublicJobsDispatchNotificationsRoute
  '/api/public/jobs/generate-forecasts': typeof ApiPublicJobsGenerateForecastsRoute
  '/api/public/jobs/process-reports': typeof ApiPublicJobsProcessReportsRoute
  '/api/public/jobs/scrape-ai-history': typeof ApiPublicJobsScrapeAiHistoryRoute
  '/api/public/jobs/scrape-planning': typeof ApiPublicJobsScrapePlanningRoute
  '/api/public/jobs/scrape-smgeag': typeof ApiPublicJobsScrapeSmgeagRoute
  '/api/public/jobs/scrape-social-signals': typeof ApiPublicJobsScrapeSocialSignalsRoute
  '/api/public/jobs/send-trial-emails': typeof ApiPublicJobsSendTrialEmailsRoute
  '/api/public/outages/ingest': typeof ApiPublicOutagesIngestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/abonnements': typeof AbonnementsRoute
  '/admin': typeof AdminRoute
  '/carte': typeof CarteRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/ma-commune': typeof MaCommuneRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/jobs/backfill-planning': typeof ApiPublicJobsBackfillPlanningRoute
  '/api/public/jobs/check-preventive': typeof ApiPublicJobsCheckPreventiveRoute
  '/api/public/jobs/cleanup-history': typeof ApiPublicJobsCleanupHistoryRoute
  '/api/public/jobs/dispatch-notifications': typeof ApiPublicJobsDispatchNotificationsRoute
  '/api/public/jobs/generate-forecasts': typeof ApiPublicJobsGenerateForecastsRoute
  '/api/public/jobs/process-reports': typeof ApiPublicJobsProcessReportsRoute
  '/api/public/jobs/scrape-ai-history': typeof ApiPublicJobsScrapeAiHistoryRoute
  '/api/public/jobs/scrape-planning': typeof ApiPublicJobsScrapePlanningRoute
  '/api/public/jobs/scrape-smgeag': typeof ApiPublicJobsScrapeSmgeagRoute
  '/api/public/jobs/scrape-social-signals': typeof ApiPublicJobsScrapeSocialSignalsRoute
  '/api/public/jobs/send-trial-emails': typeof ApiPublicJobsSendTrialEmailsRoute
  '/api/public/outages/ingest': typeof ApiPublicOutagesIngestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/abonnements'
    | '/admin'
    | '/carte'
    | '/cgu'
    | '/confidentialite'
    | '/connexion'
    | '/ma-commune'
    | '/checkout/return'
    | '/api/public/jobs/backfill-planning'
    | '/api/public/jobs/check-preventive'
    | '/api/public/jobs/cleanup-history'
    | '/api/public/jobs/dispatch-notifications'
    | '/api/public/jobs/generate-forecasts'
    | '/api/public/jobs/process-reports'
    | '/api/public/jobs/scrape-ai-history'
    | '/api/public/jobs/scrape-planning'
    | '/api/public/jobs/scrape-smgeag'
    | '/api/public/jobs/scrape-social-signals'
    | '/api/public/jobs/send-trial-emails'
    | '/api/public/outages/ingest'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/abonnements'
    | '/admin'
    | '/carte'
    | '/cgu'
    | '/confidentialite'
    | '/connexion'
    | '/ma-commune'
    | '/checkout/return'
    | '/api/public/jobs/backfill-planning'
    | '/api/public/jobs/check-preventive'
    | '/api/public/jobs/cleanup-history'
    | '/api/public/jobs/dispatch-notifications'
    | '/api/public/jobs/generate-forecasts'
    | '/api/public/jobs/process-reports'
    | '/api/public/jobs/scrape-ai-history'
    | '/api/public/jobs/scrape-planning'
    | '/api/public/jobs/scrape-smgeag'
    | '/api/public/jobs/scrape-social-signals'
    | '/api/public/jobs/send-trial-emails'
    | '/api/public/outages/ingest'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/abonnements'
    | '/admin'
    | '/carte'
    | '/cgu'
    | '/confidentialite'
    | '/connexion'
    | '/ma-commune'
    | '/checkout/return'
    | '/api/public/jobs/backfill-planning'
    | '/api/public/jobs/check-preventive'
    | '/api/public/jobs/cleanup-history'
    | '/api/public/jobs/dispatch-notifications'
    | '/api/public/jobs/generate-forecasts'
    | '/api/public/jobs/process-reports'
    | '/api/public/jobs/scrape-ai-history'
    | '/api/public/jobs/scrape-planning'
    | '/api/public/jobs/scrape-smgeag'
    | '/api/public/jobs/scrape-social-signals'
    | '/api/public/jobs/send-trial-emails'
    | '/api/public/outages/ingest'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AbonnementsRoute: typeof AbonnementsRoute
  AdminRoute: typeof AdminRoute
  CarteRoute: typeof CarteRoute
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  MaCommuneRoute: typeof MaCommuneRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicJobsBackfillPlanningRoute: typeof ApiPublicJobsBackfillPlanningRoute
  ApiPublicJobsCheckPreventiveRoute: typeof ApiPublicJobsCheckPreventiveRoute
  ApiPublicJobsCleanupHistoryRoute: typeof ApiPublicJobsCleanupHistoryRoute
  ApiPublicJobsDispatchNotificationsRoute: typeof ApiPublicJobsDispatchNotificationsRoute
  ApiPublicJobsGenerateForecastsRoute: typeof ApiPublicJobsGenerateForecastsRoute
  ApiPublicJobsProcessReportsRoute: typeof ApiPublicJobsProcessReportsRoute
  ApiPublicJobsScrapeAiHistoryRoute: typeof ApiPublicJobsScrapeAiHistoryRoute
  ApiPublicJobsScrapePlanningRoute: typeof ApiPublicJobsScrapePlanningRoute
  ApiPublicJobsScrapeSmgeagRoute: typeof ApiPublicJobsScrapeSmgeagRoute
  ApiPublicJobsScrapeSocialSignalsRoute: typeof ApiPublicJobsScrapeSocialSignalsRoute
  ApiPublicJobsSendTrialEmailsRoute: typeof ApiPublicJobsSendTrialEmailsRoute
  ApiPublicOutagesIngestRoute: typeof ApiPublicOutagesIngestRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ma-commune': {
      id: '/ma-commune'
      path: '/ma-commune'
      fullPath: '/ma-commune'
      preLoaderRoute: typeof MaCommuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnements': {
      id: '/abonnements'
      path: '/abonnements'
      fullPath: '/abonnements'
      preLoaderRoute: typeof AbonnementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/outages/ingest': {
      id: '/api/public/outages/ingest'
      path: '/api/public/outages/ingest'
      fullPath: '/api/public/outages/ingest'
      preLoaderRoute: typeof ApiPublicOutagesIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/send-trial-emails': {
      id: '/api/public/jobs/send-trial-emails'
      path: '/api/public/jobs/send-trial-emails'
      fullPath: '/api/public/jobs/send-trial-emails'
      preLoaderRoute: typeof ApiPublicJobsSendTrialEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/scrape-social-signals': {
      id: '/api/public/jobs/scrape-social-signals'
      path: '/api/public/jobs/scrape-social-signals'
      fullPath: '/api/public/jobs/scrape-social-signals'
      preLoaderRoute: typeof ApiPublicJobsScrapeSocialSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/scrape-smgeag': {
      id: '/api/public/jobs/scrape-smgeag'
      path: '/api/public/jobs/scrape-smgeag'
      fullPath: '/api/public/jobs/scrape-smgeag'
      preLoaderRoute: typeof ApiPublicJobsScrapeSmgeagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/scrape-planning': {
      id: '/api/public/jobs/scrape-planning'
      path: '/api/public/jobs/scrape-planning'
      fullPath: '/api/public/jobs/scrape-planning'
      preLoaderRoute: typeof ApiPublicJobsScrapePlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/scrape-ai-history': {
      id: '/api/public/jobs/scrape-ai-history'
      path: '/api/public/jobs/scrape-ai-history'
      fullPath: '/api/public/jobs/scrape-ai-history'
      preLoaderRoute: typeof ApiPublicJobsScrapeAiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/process-reports': {
      id: '/api/public/jobs/process-reports'
      path: '/api/public/jobs/process-reports'
      fullPath: '/api/public/jobs/process-reports'
      preLoaderRoute: typeof ApiPublicJobsProcessReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/generate-forecasts': {
      id: '/api/public/jobs/generate-forecasts'
      path: '/api/public/jobs/generate-forecasts'
      fullPath: '/api/public/jobs/generate-forecasts'
      preLoaderRoute: typeof ApiPublicJobsGenerateForecastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/dispatch-notifications': {
      id: '/api/public/jobs/dispatch-notifications'
      path: '/api/public/jobs/dispatch-notifications'
      fullPath: '/api/public/jobs/dispatch-notifications'
      preLoaderRoute: typeof ApiPublicJobsDispatchNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/cleanup-history': {
      id: '/api/public/jobs/cleanup-history'
      path: '/api/public/jobs/cleanup-history'
      fullPath: '/api/public/jobs/cleanup-history'
      preLoaderRoute: typeof ApiPublicJobsCleanupHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/check-preventive': {
      id: '/api/public/jobs/check-preventive'
      path: '/api/public/jobs/check-preventive'
      fullPath: '/api/public/jobs/check-preventive'
      preLoaderRoute: typeof ApiPublicJobsCheckPreventiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/backfill-planning': {
      id: '/api/public/jobs/backfill-planning'
      path: '/api/public/jobs/backfill-planning'
      fullPath: '/api/public/jobs/backfill-planning'
      preLoaderRoute: typeof ApiPublicJobsBackfillPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AbonnementsRoute: AbonnementsRoute,
  AdminRoute: AdminRoute,
  CarteRoute: CarteRoute,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  MaCommuneRoute: MaCommuneRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicJobsBackfillPlanningRoute: ApiPublicJobsBackfillPlanningRoute,
  ApiPublicJobsCheckPreventiveRoute: ApiPublicJobsCheckPreventiveRoute,
  ApiPublicJobsCleanupHistoryRoute: ApiPublicJobsCleanupHistoryRoute,
  ApiPublicJobsDispatchNotificationsRoute:
    ApiPublicJobsDispatchNotificationsRoute,
  ApiPublicJobsGenerateForecastsRoute: ApiPublicJobsGenerateForecastsRoute,
  ApiPublicJobsProcessReportsRoute: ApiPublicJobsProcessReportsRoute,
  ApiPublicJobsScrapeAiHistoryRoute: ApiPublicJobsScrapeAiHistoryRoute,
  ApiPublicJobsScrapePlanningRoute: ApiPublicJobsScrapePlanningRoute,
  ApiPublicJobsScrapeSmgeagRoute: ApiPublicJobsScrapeSmgeagRoute,
  ApiPublicJobsScrapeSocialSignalsRoute: ApiPublicJobsScrapeSocialSignalsRoute,
  ApiPublicJobsSendTrialEmailsRoute: ApiPublicJobsSendTrialEmailsRoute,
  ApiPublicOutagesIngestRoute: ApiPublicOutagesIngestRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
